spring.application.name=trachunom
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=trachunom;encrypt=false;
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.username=sa
#spring.datasource.password=123456
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.datasource.url=jdbc:postgresql://localhost:5432/trachunom
spring.datasource.username=Liu
spring.datasource.password=123456
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

logging.level.org.springframework=INFO
logging.level.com.vaadin=INFO
logging.level.org.hibernate=INFO


# Vaadin configuration
vaadin.launch-browser=false
vaadin.whitelisted-packages=com.liu.trachunom
vaadin.pnpm.enable=false
vaadin.productionMode=false
vaadin.frontend.ci=true
vaadin.allowed-packages=com.vaadin,org.vaadin


# Server configuration
server.port=8080
server.servlet.session.timeout=30m
server.address=0.0.0.0

# Disable Spring DevTools to avoid conflicts with Vaadin
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false
